# Generated by Django 6.1.1 on 2026-09-19 00:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=250, verbose_name="عنوان")),
                (
                    "slug",
                    models.SlugField(max_length=270, unique=True, verbose_name="اسلاگ"),
                ),
                ("excerpt", models.CharField(max_length=300, verbose_name="خلاصه")),
                ("content", models.TextField(verbose_name="متن")),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="blog/", verbose_name="تصویر"
                    ),
                ),
                (
                    "published_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاریخ انتشار"),
                ),
                (
                    "author",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="posts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="نویسنده",
                    ),
                ),
            ],
            options={
                "verbose_name": "پست مجله",
                "verbose_name_plural": "پست\u200cهای مجله",
                "ordering": ["-published_at"],
            },
        ),
    ]
