# Generated by Django 6.1.1 on 2026-09-19 00:25

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Color",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=60, verbose_name="نام رنگ")),
                (
                    "hex_code",
                    models.CharField(
                        help_text="مثال: #3A2418",
                        max_length=7,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="کد رنگ باید به\u200cصورت هگز باشه، مثلاً #3A2418",
                                regex="^#(?:[0-9a-fA-F]{3}){1,2}$",
                            )
                        ],
                        verbose_name="کد هگز",
                    ),
                ),
            ],
            options={
                "verbose_name": "رنگ",
                "verbose_name_plural": "رنگ\u200cها",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Coupon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="کد تخفیف"
                    ),
                ),
                (
                    "discount_type",
                    models.CharField(
                        choices=[("percent", "درصدی"), ("fixed", "مبلغ ثابت")],
                        default="percent",
                        max_length=10,
                        verbose_name="نوع تخفیف",
                    ),
                ),
                (
                    "discount_value",
                    models.PositiveIntegerField(
                        help_text="اگر درصدی  ۱ تا ۱۰۰، اگر ثابت به تومان",
                        verbose_name="مقدار تخفیف",
                    ),
                ),
                (
                    "min_order_amount",
                    models.PositiveIntegerField(
                        default=0, verbose_name="حداقل مبلغ سفارش"
                    ),
                ),
                ("start_date", models.DateTimeField(verbose_name="تاریخ شروع")),
                ("end_date", models.DateTimeField(verbose_name="تاریخ پایان")),
                (
                    "usage_limit",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="خالی بگذارید یعنی نامحدود",
                        null=True,
                        verbose_name="حداکثر تعداد استفاده",
                    ),
                ),
                (
                    "used_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="تعداد استفاده\u200cشده"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
            ],
            options={
                "verbose_name": "کد تخفیف",
                "verbose_name_plural": "کدهای تخفیف",
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=150, verbose_name="نام دسته\u200cبندی"),
                ),
                (
                    "slug",
                    models.SlugField(max_length=170, unique=True, verbose_name="اسلاگ"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="ترتیب نمایش"),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="shop.category",
                        verbose_name="دسته والد",
                    ),
                ),
            ],
            options={
                "verbose_name": "دسته\u200cبندی",
                "verbose_name_plural": "دسته\u200cبندی\u200cها",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="نام محصول")),
                (
                    "slug",
                    models.SlugField(max_length=220, unique=True, verbose_name="اسلاگ"),
                ),
                (
                    "short_description",
                    models.CharField(max_length=300, verbose_name="توضیحات کوتاه"),
                ),
                ("full_description", models.TextField(verbose_name="توضیحات کامل")),
                ("price", models.PositiveIntegerField(verbose_name="قیمت (تومان)")),
                (
                    "discount_percent",
                    models.PositiveIntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="درصد تخفیف",
                    ),
                ),
                (
                    "stock",
                    models.PositiveIntegerField(default=0, verbose_name="موجودی"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
                (
                    "material",
                    models.CharField(
                        help_text="مثال: چرم طبیعی گاوی، چرم ساخت روسیه",
                        max_length=100,
                        verbose_name="جنس محصول",
                    ),
                ),
                (
                    "main_image",
                    models.ImageField(upload_to="products/", verbose_name="تصویر اصلی"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "is_best_seller",
                    models.BooleanField(default=False, verbose_name="پرفروش"),
                ),
                ("is_new", models.BooleanField(default=False, verbose_name="جدید")),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="products",
                        to="shop.category",
                        verbose_name="دسته\u200cبندی",
                    ),
                ),
                (
                    "colors",
                    models.ManyToManyField(
                        blank=True,
                        related_name="products",
                        to="shop.color",
                        verbose_name="رنگ\u200cها",
                    ),
                ),
            ],
            options={
                "verbose_name": "محصول",
                "verbose_name_plural": "محصولات",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="products/gallery/", verbose_name="تصویر"
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="ترتیب نمایش"),
                ),
                (
                    "is_main",
                    models.BooleanField(default=False, verbose_name="تصویر اصلی"),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="shop.product",
                        verbose_name="محصول",
                    ),
                ),
            ],
            options={
                "verbose_name": "تصویر محصول",
                "verbose_name_plural": "تصاویر محصول",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="امتیاز",
                    ),
                ),
                ("comment", models.TextField(verbose_name="متن نظر")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ثبت"),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="shop.product",
                        verbose_name="محصول",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="کاربر",
                    ),
                ),
            ],
            options={
                "verbose_name": "نظر",
                "verbose_name_plural": "نظرات",
                "ordering": ["-created_at"],
                "unique_together": {("user", "product")},
            },
        ),
        migrations.CreateModel(
            name="Wishlist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wishlisted_by",
                        to="shop.product",
                        verbose_name="محصول",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wishlist_items",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="کاربر",
                    ),
                ),
            ],
            options={
                "verbose_name": "علاقه\u200cمندی",
                "verbose_name_plural": "علاقه\u200cمندی\u200cها",
                "unique_together": {("user", "product")},
            },
        ),
    ]
