# Generated by Django 6.1.1 on 2026-09-21 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="specifications",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="به شکل json نوشته شود.",
                verbose_name="مشخصات محصول",
            ),
        ),
        migrations.AlterField(
            model_name="coupon",
            name="min_order_amount",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="خالی بگذارید یعنی بدون لیمیت (تومان)",
                null=True,
                verbose_name="حداقل مبلغ سفارش",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="full_description",
            field=models.TextField(blank=True, null=True, verbose_name="توضیحات کامل"),
        ),
        migrations.AlterField(
            model_name="product",
            name="is_new",
            field=models.BooleanField(default=True, verbose_name="جدید"),
        ),
    ]
