# Generated by Django 6.1.1 on 2026-09-19 00:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("shop", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order_number",
                    models.CharField(
                        editable=False,
                        max_length=32,
                        unique=True,
                        verbose_name="شماره سفارش",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "در انتظار پرداخت"),
                            ("paid", "پرداخت\u200cشده"),
                            ("processing", "در حال پردازش"),
                            ("shipped", "ارسال\u200cشده"),
                            ("delivered", "تحویل داده\u200cشده"),
                            ("cancelled", "لغو شده"),
                        ],
                        default="pending",
                        max_length=15,
                        verbose_name="وضعیت سفارش",
                    ),
                ),
                (
                    "total_amount",
                    models.PositiveIntegerField(
                        help_text="جمع قیمت آیتم\u200cها پیش از تخفیف",
                        verbose_name="مبلغ کل",
                    ),
                ),
                (
                    "discount_amount",
                    models.PositiveIntegerField(default=0, verbose_name="مبلغ تخفیف"),
                ),
                (
                    "shipping_cost",
                    models.PositiveIntegerField(default=0, verbose_name="هزینه ارسال"),
                ),
                (
                    "final_amount",
                    models.PositiveIntegerField(verbose_name="مبلغ نهایی"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ثبت"),
                ),
                (
                    "coupon",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="orders",
                        to="shop.coupon",
                        verbose_name="کد تخفیف استفاده\u200cشده",
                    ),
                ),
                (
                    "shipping_address",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="orders",
                        to="accounts.address",
                        verbose_name="آدرس ارسال",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="orders",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="کاربر",
                    ),
                ),
            ],
            options={
                "verbose_name": "سفارش",
                "verbose_name_plural": "سفارش\u200cها",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "product_name_snapshot",
                    models.CharField(
                        editable=False,
                        max_length=200,
                        verbose_name="نام محصول (در زمان خرید)",
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(default=1, verbose_name="تعداد"),
                ),
                (
                    "price_at_purchase",
                    models.PositiveIntegerField(
                        verbose_name="قیمت محصول در زمان خرید (تومان)"
                    ),
                ),
                (
                    "final_amount",
                    models.PositiveIntegerField(
                        help_text="price_at_purchase × quantity",
                        verbose_name="مبلغ نهایی این آیتم",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="orders.order",
                        verbose_name="سفارش",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="order_items",
                        to="shop.product",
                        verbose_name="محصول",
                    ),
                ),
            ],
            options={
                "verbose_name": "آیتم سفارش",
                "verbose_name_plural": "آیتم\u200cهای سفارش",
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.PositiveIntegerField(verbose_name="مبلغ")),
                (
                    "tracking_code",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="شماره پیگیری"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "در انتظار"),
                            ("success", "موفق"),
                            ("failed", "ناموفق"),
                        ],
                        default="pending",
                        max_length=10,
                        verbose_name="وضعیت پرداخت",
                    ),
                ),
                (
                    "gateway",
                    models.CharField(
                        help_text="مثال: زرین\u200cپال و ...",
                        max_length=50,
                        verbose_name="درگاه پرداخت",
                    ),
                ),
                (
                    "paid_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاریخ پرداخت"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ثبت"),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="orders.order",
                        verbose_name="سفارش",
                    ),
                ),
            ],
            options={
                "verbose_name": "پرداخت",
                "verbose_name_plural": "پرداخت\u200cها",
                "ordering": ["-created_at"],
            },
        ),
    ]
